language: node_js

node_js:
  - '12.8.0'

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn --frozen-lockfile

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - yarn run test
